base = {
    "show": "all",
    "daterange": "3",
    "ls": "all",
    "loc": "us",
    "sort": "new",
    "marketcap_l": "0",
    "marketcap_h": "500000000000",
    "rtr_l": "",
    "rtr_h": "",
    "country": "",
    "state": "",
    "aum": "",
    "yio": "",
    "gotodate": "02/02/2025",
    "page": "1",
    "end_page": "1",
    "is_login": "1",
}
